stages:
  - build
  - deploy

# Docker Build and Push to ECR
build_and_push_backend_redis:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u AWS -p $(aws ecr get-login-password --region eu-central-1) 891612544658.dkr.ecr.eu-central-1.amazonaws.com
    - docker build -t backend_redis .
    - docker tag backend_redis:latest 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_redis:latest
    - docker push 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_redis:latest

build_and_push_backend_rds:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u AWS -p $(aws ecr get-login-password --region eu-central-1) 891612544658.dkr.ecr.eu-central-1.amazonaws.com
    - docker build -t backend_rds .
    - docker tag backend_rds:latest 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_rds:latest
    - docker push 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_rds:latest

# Deploy to EC2
deploy_backend_to_ec2:
  stage: deploy
  image: ruby:2.7
  before_script:
    - apt-get update -y
    - apt-get install -y sshpass
  script:
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ubuntu@18.197.122.99 'docker pull 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_redis:latest && docker pull 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_rds:latest && docker-compose -f /path/to/your/docker-compose.yml up -d'
