stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-central-1"
  ECR_REGISTRY: "891612544658.dkr.ecr.eu-central-1.amazonaws.com"
  BACKEND_RDS_REPO: "$ECR_REGISTRY/backend-rds"
  BACKEND_REDIS_REPO: "$ECR_REGISTRY/backend_redis"
  IMAGE_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  DOCKER_DRIVER: overlay2  # Задаємо драйвер для Docker

# Використовуємо образ Docker для запуску пайплайну з Docker-in-Docker
image: docker:latest

before_script:
  - apk add --no-cache py3-pip python3  # Встановлення Python та PIP
  - python3 -m venv /venv  # Створення віртуального середовища
  - . /venv/bin/activate  # Активуємо віртуальне середовище
  - pip install --upgrade pip  # Оновлюємо pip в віртуальному середовищі
  - pip install --upgrade awscli  # Встановлюємо AWS CLI
  - aws --version  # Перевіряємо версію AWS CLI
  - echo "Logging into Amazon ECR..."
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

services:
  - docker:19.03.12-dind  # Використовуємо Docker-in-Docker

build_backend_rds:
  stage: build
  script:
    - echo "Building Docker image for backend_rds..."
    - docker build -t $BACKEND_RDS_REPO:$IMAGE_TAG -f backend_rds/Dockerfile .

build_backend_redis:
  stage: build
  script:
    - echo "Building Docker image for backend_redis..."
    - docker build -t $BACKEND_REDIS_REPO:$IMAGE_TAG -f backend_redis/Dockerfile .

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - echo "Deploying backend_rds image with tag $IMAGE_TAG"
    - echo "Deploying backend_redis image with tag $IMAGE_TAG"
    # Додати команди для деплою через AWS CLI, ECS CLI або вручну через SSH.
