stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-central-1"
  ECR_REGISTRY: "891612544658.dkr.ecr.eu-central-1.amazonaws.com"
  BACKEND_RDS_REPO: "$ECR_REGISTRY/backend-rds"
  BACKEND_REDIS_REPO: "$ECR_REGISTRY/backend_redis"
  IMAGE_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

# Використовуємо базовий образ Ubuntu
image: ubuntu:22.04

before_script:
  - apt-get update && apt-get install -y curl jq python3 python3-venv docker.io
  - python3 -m venv /venv
  - . /venv/bin/activate
  - pip install --upgrade pip
  - pip install --upgrade awscli
  - aws --version
  - echo "Logging into Amazon ECR..."
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

build_backend_rds:
  stage: build
  script:
    - echo "Building Docker image for backend_redis..."
    - docker build -t $BACKEND_REDIS_REPO:$IMAGE_TAG -f backend_redis/Dockerfile .

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - echo "Deploying backend_rds image with tag $IMAGE_TAG"
    - echo "Deploying backend_redis image with tag $IMAGE_TAG"
    # Додати команди для деплою через AWS CLI, ECS CLI або вручну через SSH.
