stages:
  - build
  - deploy

variables:
  ECR_REGISTRY: "891612544658.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"  # Використовуємо конкретний реєстр для ECR
  IMAGE_TAG: "$CI_COMMIT_REF_NAME+$(echo $CI_COMMIT_SHA | head -c 7)"  # Визначаємо тег, що включає гілку і короткий хеш

# Використовуємо Ubuntu як базовий образ
image: ubuntu:20.04

before_script:
  # Оновлюємо пакети та встановлюємо AWS CLI
  - apt-get update -y
  - apt-get install -y awscli docker.io

build_backend_rds:
  stage: build
  variables:
    ECR_REPOSITORY: "backend-rds"  # Репозиторій для backend_rds
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - cd backend_rds
    - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

build_backend_redis:
  stage: build
  variables:
    ECR_REPOSITORY: "backend_redis"  # Репозиторій для backend_redis
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - cd backend_redis
    - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" > private_key.pem
    - chmod 600 private_key.pem
    - ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_HOST "
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY;
        docker pull $ECR_REGISTRY/backend-rds:$IMAGE_TAG;
        docker pull $ECR_REGISTRY/backend_redis:$IMAGE_TAG;
        docker-compose down;
        docker-compose up -d"
