stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-central-1"
  ECR_REGISTRY: "891612544658.dkr.ecr.eu-central-1.amazonaws.com"
  BACKEND_RDS_REPO: "$ECR_REGISTRY/backend-rds"
  BACKEND_REDIS_REPO: "$ECR_REGISTRY/backend_redis"
  IMAGE_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"  

# Аутентифікація до ECR
before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'bash -s' < ./deploy.sh
  only:
    - master
