version: '3.8'

services:
  backend_rds:
    image: 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_rds:main-580f1ae4
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://dwl2e3x2kooo5.cloudfront.net
    ports:
      - "8000:8000"

  backend_redis:
    image: 891612544658.dkr.ecr.eu-central-1.amazonaws.com/backend_redis:main-580f1ae4
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_DB=${REDIS_DB}
      - CORS_ALLOWED_ORIGINS=http://dwl2e3x2kooo5.cloudfront.net
    ports:
      - "8001:8001"
